version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql
    command: [ "--default-authentication-plugin=mysql_native_password" ]
    volumes:
      - db:/var/lib/mysql
    restart: always
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password0
      MYSQL_DATABASE: symfony-demo
      MYSQL_USER: symfony-demo
      MYSQL_PASSWORD: symfony-demo

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "6802:80"
    environment:
      - PMA_ARBITRARY=1

  php:
    container_name: php
    build:
      context: ./Php
    volumes:
      - ../Symfony:/var/www
    ports:
      - '9000:9000'
    depends_on:
      - db

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ../Symfony:/var/www
      - ./Nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db

volumes:
  db: { }

